name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Node Setup
        uses: actions/setup-node@v2.1.2

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Bootstrap
        run: npm run bootstrap

      - name: Transpile
        run: npm run build

      - name: Lint
        run: npm run test:lint

      - name: Unit Tests
        run: npm run test:unit

      # No e2e tests for now
      #- name: E2E Tests
        #run: npm run test:e2e
